### ISSUE TITLE
Display a call to action to install the web extension when window.ipfs is missing

### ISSUE THREAD

**Issue by lidel** [hacdias/ipfs-id-qr-codes-example#1]
> @alanshaw  if no `window.ipfs` then it needs a call to action to install the web extension
> @lidel that is a very good idea, we could have a ready-to-use snippet that displays non-modal monit to install ipfs companion, like in the old browser wars days :) https://www.philweber.com/images/infobar.png but less ugly ;)

## Background
I remember Cloudflare having a checkbox to add js to your page that detected Internet Explorer and displayed a trollish yellow bar (that looks like native one i linked above) asking user to upgrade to a modern browser  with a link to the landing page that had some info about firefox, chrome, opera and others.

I think we could do something similar when we detect lack of `window.ipfs`.

Link we could use: https://github.com/ipfs/ipfs-companion#install or https://github.com/ipfs-shipyard/ipfs-companion/issues/439 (when done)

**Comment by alanshaw** [comment]
I'd like to use this in other demo projects so a separate module/standalone script I can embed on the page would be aces.

**Comment by hacdias** [comment]
@alanshaw @lidel boom: https://github.com/ipfs-shipyard/window.ipfs-is-required
